env:
  es2021: true
  node: true
  jest: true
extends: airbnb-base
overrides:
  [
    {
      files: ["index.test.js", "gendiff.js", index.js],
      rules:
        {
          "import/extensions": "off",
          "no-underscore-dangle": "off",
          "no-console": "off",
          "import/no-extraneous-dependencies": "off",
        },
    },
  ]
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {}
